title: "Mi Site de Pruebas"
description: "Este es un sitio de pruebas para GitHub Pages con Jekyll."
author: "Ruben"
email: "rubenparapruebas@gmail.com"
baseurl: ""
url: "https://rubenparapruebas.github.io"
theme: minima # Tema básico que viene con Jekyll
